/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClockPanel.java
 *
 * Created on 14-04-2009, 12:18:22 PM
 */

package com.leopard2av.clock;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;
import javax.swing.text.DateFormatter;
import org.openide.util.Exceptions;

/**
 * A simple clock/calendar plugin for Netbeans 6.5
 *
 * @author leopard (aka leopard2av on some places) pedro.oyarce@gmail.com
 */
public class ClockPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = -5149030714157897159L;

    /** Creates new form ClockPanel */
    public ClockPanel() {
        initComponents();
        start();
    }

    /**
     * Start the timer
     */
    private void start() {
        Runnable timer = new Runnable() {
            public void run() {
                while(true) {
                    SwingUtilities.invokeLater(new Runnable() {

                        public void run() {
                           showHour();
                        }
                    });
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                }
            }
        };
        new Thread(timer).start();
    }

    /**
     * Show hour & time in JLabels
     */
    private void showHour() {
        try {
            dateLbl.setText(new DateFormatter().valueToString(new Date()));
        } catch (ParseException ex) {
            Exceptions.printStackTrace(ex);
        }
         hourLbl.setText(new SimpleDateFormat("HH:mm:ss").format(new Date()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        hourLbl = new javax.swing.JLabel();

        setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leopard2av/clock/fecha.png"))); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ClockPanel.class, "ClockPanel.jLabel1.text")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leopard2av/clock/hora.png"))); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(ClockPanel.class, "ClockPanel.jLabel2.text")); // NOI18N

        dateLbl.setText(org.openide.util.NbBundle.getMessage(ClockPanel.class, "ClockPanel.dateLbl.text")); // NOI18N

        hourLbl.setText(org.openide.util.NbBundle.getMessage(ClockPanel.class, "ClockPanel.hourLbl.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(hourLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        dateLbl.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ClockPanel.class, "ClockPanel.jLabel3.AccessibleContext.accessibleName")); // NOI18N
        hourLbl.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ClockPanel.class, "ClockPanel.jLabel4.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel hourLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
